FROM alpine:3.23@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62 AS certs

RUN apk --update add ca-certificates


FROM golang:1.25@sha256:0f406d34b7cb7255d0700af02ec28a2c88f1e00701055f4c282aa4c3ec0b3245 AS build-stage

WORKDIR /build

COPY ./builder-manifest.yaml builder-manifest.yaml

RUN --mount=type=cache,target=/root/.cache/go-build GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder@v0.139.0
RUN --mount=type=cache,target=/root/.cache/go-build builder --config builder-manifest.yaml


FROM alpine:3.23@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62

RUN apk --no-cache add ca-certificates util-linux

ARG USER_UID=10001
RUN adduser -D -u ${USER_UID} otel
USER ${USER_UID}

COPY --chmod=755 --from=build-stage /build/dist/otelcol-ebpf-profiler-custom /otelcol/otelcol-ebpf-profiler-custom

ENTRYPOINT ["/otelcol/otelcol-ebpf-profiler-custom"]
CMD ["--config", "/conf/relay.yaml"]

EXPOSE 4317 4318 13133 14250 14268 6831 9411
