FROM alpine:3.24@sha256:5b02b42e375f7426f8d65c3af331ca05d9878f9989230354504e0b9dfd431f60 AS certs

RUN apk --update add ca-certificates


FROM golang:1.27@sha256:f44f6e88636cfb311f9ebace870ded69d943f227bb3cb27d32ffd84ea18c43ea AS build-stage

WORKDIR /build

COPY ./builder-manifest.yaml builder-manifest.yaml

RUN --mount=type=cache,target=/root/.cache/go-build GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder@v0.139.0
RUN --mount=type=cache,target=/root/.cache/go-build builder --config builder-manifest.yaml


FROM alpine:3.24@sha256:5b02b42e375f7426f8d65c3af331ca05d9878f9989230354504e0b9dfd431f60

RUN apk --no-cache add ca-certificates util-linux

ARG USER_UID=10001
RUN adduser -D -u ${USER_UID} otel
USER ${USER_UID}

COPY --chmod=755 --from=build-stage /build/dist/otelcol-ebpf-profiler-custom /otelcol/otelcol-ebpf-profiler-custom

ENTRYPOINT ["/otelcol/otelcol-ebpf-profiler-custom"]
CMD ["--config", "/conf/relay.yaml"]

EXPOSE 4317 4318 13133 14250 14268 6831 9411
