FROM alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659 AS certs

RUN apk --update add ca-certificates


FROM golang:1.25@sha256:cc737435e2742bd6da3b7d575623968683609a3d2e0695f9d85bee84071c08e6 AS build-stage

WORKDIR /build

COPY ./builder-manifest.yaml builder-manifest.yaml

RUN --mount=type=cache,target=/root/.cache/go-build GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder@v0.139.0
RUN --mount=type=cache,target=/root/.cache/go-build builder --config builder-manifest.yaml


FROM alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

RUN apk --no-cache add ca-certificates util-linux

ARG USER_UID=10001
RUN adduser -D -u ${USER_UID} otel
USER ${USER_UID}

COPY --chmod=755 --from=build-stage /build/dist/otelcol-ebpf-profiler-custom /otelcol/otelcol-ebpf-profiler-custom

ENTRYPOINT ["/otelcol/otelcol-ebpf-profiler-custom"]
CMD ["--config", "/conf/relay.yaml"]

EXPOSE 4317 4318 13133 14250 14268 6831 9411
