on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

# Set default permissions as read only.
permissions: read-all

name: profcheck
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-latest, macos-latest]
        go-version: ['oldstable', 'stable']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum
          check-latest: true
      - name: tests
        run: |
          go test -C profcheck/ ./...
